[package]
name = "py-regex"
version = "0.1.1"
edition = "2024"
description = "A small wrapper around the Python regex module via PyO3."
license = "MIT"

[dependencies]
pyo3 = { version = "0.24.1", features = ["auto-initialize"] }
